export const siteConfig = {
  name: "CNicole Stylez",
  tagline: "Personal Stylist",
  founder: "Cheryl Nicole",
  email: "Connect@cnicolestylez.com",
  phone: "(253) 544-7568",
  phoneHref: "tel:2534417714",
  instagram: "@cnicoles_stylez",
  instagramUrl: "https://www.instagram.com/cnicoles_stylez/",
  tiktok: "@cnicolestylez",
  tiktokUrl: "https://www.tiktok.com/@cnicolestylez",
  website: "CNicoleStylez.com",
  websiteUrl: "https://CNicoleStylez.com",
  copyrightYear: "2025",
} as const;
